version: '3.9'

volumes:
  postgres_data: { }

x-app-as-service: &app_as_service
  build: .
  environment:
    - POSTGRES_HOST=postgres
    - POSTGRES_PORT=5432
    - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
  env_file:
    - .env
  depends_on:
    - postgres
  profiles:
    - full_dev

services:
  app:
    <<: *app_as_service
    command: /start.sh

  postgres:
    image: postgres:15.4
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    profiles:
        - full_dev
        - local_dev
        - pgadmin

  pgadmin:
    image: dpage/pgadmin4:7.6
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@mail.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin123}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    profiles:
      - pgadmin

  rabbitmq:
    image: rabbitmq:3.11.4-management-alpine
    profiles:
      - full_dev


  celery-worker:
    <<: *app_as_service
    command: /celery_worker_start.sh

  celery-beat:
    <<: *app_as_service
    command: /celery_beat_start.sh

#  nginx:
#    build: ./nginx
#    ports:
#      - 1337:80
#    profiles:
#      - local_dev
#    depends_on:
#      - app