# Generated by Django 4.2.5 on 2023-09-29 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="user",
        ),
        migrations.RemoveField(
            model_name="kindofservice",
            name="user",
        ),
        migrations.RemoveField(
            model_name="service",
            name="user",
        ),
    ]
