# Generated by Django 4.2.5 on 2023-09-30 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(default="Started", max_length=10)),
                ("manually_closed", models.BooleanField(default=False)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="services.client")),
                ("service", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="services.service")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
