# Generated by Django 4.2.5 on 2023-10-05 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_action"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CurrencyRate",
        ),
    ]
