# Generated by Django 4.2.5 on 2023-10-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0007_refofcurrency_currencyrate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currencyrate",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="currencyrate",
            name="last_updated",
        ),
        migrations.RemoveField(
            model_name="currencyrate",
            name="user",
        ),
        migrations.AddField(
            model_name="currencyrate",
            name="currency_code",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AlterField(
            model_name="currencyrate",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name="RefOfCurrency",
        ),
    ]
