# Generated by Django 4.2.5 on 2023-09-29 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_remove_client_user_remove_kindofservice_user_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="client",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="services.client"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="kind_of_service",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="services.kindofservice"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="service",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="services.service"
            ),
        ),
    ]
